global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 5s
    metrics_path: /metrics

  # Tempo metrics
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
    scrape_interval: 5s
    metrics_path: /metrics

  # .NET Applications using Package.Observability
  - job_name: 'webapi-example'
    static_configs:
      - targets: ['host.docker.internal:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # Add more .NET applications here
  # - job_name: 'my-other-service'
  #   static_configs:
  #     - targets: ['host.docker.internal:9091']
  #   scrape_interval: 5s
  #   metrics_path: /metrics